
package grafos;

import javax.swing.JOptionPane;

/**
 *
 * @author alexandrezamberlam
 * @author sylviovieira
 */
public class TelaGrafo extends javax.swing.JFrame {

    /**
     * Creates new form TelaGrafo
     */
    public TelaGrafo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLlogoUnifra = new javax.swing.JLabel();
        jbCarregarArquivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaListaDeMoleculas = new javax.swing.JTextArea();
        jlMoleculas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaMatrizAdjacencia = new javax.swing.JTextArea();
        jlMatriz = new javax.swing.JLabel();
        jlSobre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfMaiorGrau = new javax.swing.JTextField();
        jtfMaiorIncidencia = new javax.swing.JTextField();
        jtfMaiorPartida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbCalcular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfGrauMoleculaEscolhida = new javax.swing.JTextField();
        jcbMoleculaAnalise = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaCaminho = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matriz de Adjacência de Redes de Interação");
        setResizable(false);

        jLlogoUnifra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafos/nano.png"))); // NOI18N

        jbCarregarArquivo.setText("Carregar Arquivo de Interações");
        jbCarregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarregarArquivoActionPerformed(evt);
            }
        });

        jtaListaDeMoleculas.setColumns(20);
        jtaListaDeMoleculas.setRows(5);
        jScrollPane1.setViewportView(jtaListaDeMoleculas);

        jlMoleculas.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jlMoleculas.setText("Moléculas");

        jtaMatrizAdjacencia.setColumns(20);
        jtaMatrizAdjacencia.setRows(5);
        jScrollPane2.setViewportView(jtaMatrizAdjacencia);

        jlMatriz.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jlMatriz.setText("Matriz de Adjacência");

        jlSobre.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jlSobre.setText("Sobre");
        jlSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlSobreMousePressed(evt);
            }
        });

        jLabel1.setText("Maior conectividade:");

        jLabel2.setText("Maior incidência:");

        jLabel3.setText("Maior grau de partida:");

        jtfMaiorGrau.setEditable(false);

        jtfMaiorIncidencia.setEditable(false);

        jtfMaiorPartida.setEditable(false);

        jLabel4.setText("Escolha molécula: ");

        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });

        jLabel5.setText("Conectividade:");

        jcbMoleculaAnalise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Moléculas" }));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Caminho");

        jtaCaminho.setColumns(20);
        jtaCaminho.setRows(5);
        jScrollPane3.setViewportView(jtaCaminho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jlMoleculas)
                                .addGap(42, 42, 42)
                                .addComponent(jlMatriz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbCarregarArquivo)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLlogoUnifra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfMaiorIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtfMaiorPartida, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(jtfMaiorGrau)))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbMoleculaAnalise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfGrauMoleculaEscolhida))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCalcular)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlSobre)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(994, 994, 994)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLlogoUnifra, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlMatriz)
                            .addComponent(jbCarregarArquivo)
                            .addComponent(jlMoleculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlSobre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfMaiorGrau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jbCalcular)
                            .addComponent(jcbMoleculaAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfGrauMoleculaEscolhida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMaiorIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMaiorPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCarregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarregarArquivoActionPerformed
        jtaListaDeMoleculas.setText("");
        jtaMatrizAdjacencia.setText("");
        jtfMaiorGrau.setText("");
        jtfMaiorIncidencia.setText("");
        jtfMaiorPartida.setText("");
        jtfGrauMoleculaEscolhida.setText("");
        jcbMoleculaAnalise.removeAllItems();
        jcbMoleculaAnalise.addItem("Moléculas");
        jtaCaminho.setText("");
        
        grafo = Util.lerArquivo(Util.carregarArquivo(), jtaListaDeMoleculas, jtaMatrizAdjacencia);
        if (grafo != null) {
            jtfMaiorGrau.setText(grafo.calcularMaiorGrau());
            jtfMaiorIncidencia.setText(grafo.calcularMaiorIncidencia());
            jtfMaiorPartida.setText(grafo.calcularMaiorPartida());
            for (int i = 0; i < grafo.listaMoleculas.size(); i++) {
                jcbMoleculaAnalise.addItem(grafo.listaMoleculas.get(i));
            }
        }
    }//GEN-LAST:event_jbCarregarArquivoActionPerformed

    private void jlSobreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSobreMousePressed
        JOptionPane.showMessageDialog(this, 
                  "Software de Geração de Matriz de Adjacência"
                + "\nDisciplina de BioInformática"
                + "\nProfessores: Eder Simão e Solange Hoezel"
                + "\nAutores: Alexandre Zamberlan e Sylvio Vieira","Sobre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jlSobreMousePressed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        if (grafo != null && jcbMoleculaAnalise.getSelectedIndex() > 0) {
            jtfGrauMoleculaEscolhida.setText("" + grafo.calcularGrau(jcbMoleculaAnalise.getSelectedItem().toString()));
            jtaCaminho.append(grafo.mostrarCaminho(jcbMoleculaAnalise.getSelectedItem().toString()));
            //grafo.mostrarCaminho(jcbMoleculaAnalise.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jbCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGrafo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLlogoUnifra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbCarregarArquivo;
    private javax.swing.JComboBox jcbMoleculaAnalise;
    private javax.swing.JLabel jlMatriz;
    private javax.swing.JLabel jlMoleculas;
    private javax.swing.JLabel jlSobre;
    private javax.swing.JTextArea jtaCaminho;
    private javax.swing.JTextArea jtaListaDeMoleculas;
    private javax.swing.JTextArea jtaMatrizAdjacencia;
    private javax.swing.JTextField jtfGrauMoleculaEscolhida;
    private javax.swing.JTextField jtfMaiorGrau;
    private javax.swing.JTextField jtfMaiorIncidencia;
    private javax.swing.JTextField jtfMaiorPartida;
    // End of variables declaration//GEN-END:variables
    private Grafo grafo;
}
